wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: huggingface
    huggingface_version: 4.2.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 1
      4: 3.7.9
      5: 0.10.15
      6: 4.2.2
data_dir:
  desc: null
  value: /home/dc925/project/data/graphmimic/sample/
learning_rate:
  desc: null
  value: 2.0e-05
max_seq_length:
  desc: null
  value: 128
model_name_or_path:
  desc: null
  value: xhlu/electra-medal
num_train_epochs:
  desc: null
  value: 4
output_dir:
  desc: null
  value: /home/dc925/project/output/129/wandb
per_gpu_eval_batch_size:
  desc: null
  value: 32
per_gpu_train_batch_size:
  desc: null
  value: 32
